---
- name: Config Elk Docker
  hosts: elkservers
  become: true
  tasks:
  - name: set vm.max_map_count to 262144 in sysctl
    sysctl: name={{ item.key }} value={{ item.value }}
    with_items:
      - { key: "vm.max_map_count", value: "262144" }
  - name: docker.io
    apt:
      force_apt_get: yes
      name: docker.io
      state: present

  - name: Install pip
    apt:
      force_apt_get: yes
      name: python-pip
      state: present

  - name: Install Docker python module
    pip:
      name: docker
      state: present


  - name: elk Dl
    docker_container:
      name: elk
      image: sebp/elk
      state: started
      ports:
        - "5601:5601"
        - "9200:9200"
        - "5044:5044"

